name: Deploy Docker Image to EC2 Kubernetes Cluster

on:
  push:
    branches:
      - test  # Trigger on push to the 'test' branch (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1  # AWS region
      AWS_ACCOUNT_ID: 863518440386  # AWS account ID
      ECR_REPOSITORY: ashok_hotel  # Name of your ECR repository
      IMAGE_TAG: latest  # The tag of the image (latest in your case)
      EC2_IP: 3.93.23.38  # Public IP of your EC2 instance
      EC2_USER: ubuntu  # SSH user for EC2 (commonly 'ubuntu' for Ubuntu-based instances)
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key (stored in GitHub Secrets)

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials (for ECR authentication)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Authenticate Docker to AWS ECR
      - name: Authenticate Docker to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }}
      # Step 4: Pull the Docker image from ECR
      - name: Pull Docker image from ECR
        run: |
          docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

